Hindu=[
"Aaru Nattu Vellala",
"Achirapakkam Chettiar",
"Ad Dharmi",
"Adi Andhra",
"Adi Dravidar",
"Adi Karnataka",
"Agamudayar / Arcot / Thuluva Vellala",
"Agaram Vellan Chettiar",
"Agarwal",
"Agnikula Kshatriya",
"Agrahari",
"Agri",
"Aguri / Ugra Kshatriya",
"Aheriya",
"Ahir Shimpi",
"Ahirwar",
"Ahom",
"Ambalavasi",
"Amma Kodava",
"Anjana (Chowdary) Patel",
"Arakh / Arakvanshiya",
"Aramari / Gabit",
"Arekatica",
"Arora",
"Arunthathiyar",
"Arya Vysya",
"Asathi",
"Ayira Vysya",
"Ayodhyavasi",
"Ayyaraka",
"Badaga",
"Bagdi",
"Baidya",
"Bairagi",
"Bairwa",
"Baishnab",
"Baishya",
"Bajantri",
"Balai",
"Balija",
"Balija Naidu",
"Balija Reddy",
"Banayat Oriya",
"Banik",
"Baniya",
"Baniya - Bania",
"Baniya - Kumuti",
"Banjara",
"Baori",
"Barai",
"Bargi",
"Bari",
"Baria",
"Barnwal",
"Barujibi",
"Bavaria",
"Bazigar",
"Beldar",
"Beri Chettiar",
"Besta",
"Bhand",
"Bhandari",
"Bhar",
"Bharbhunja",
"Bhatia",
"Bhatraju",
"Bhavasar Kshatriya",
"Bhil",
"Bhoi",
"Bhovi",
"Bhoyar",
"Bhulia / Meher",
"Billava",
"Bind",
"Bishnoi/Vishnoi",
"Bondili",
"Boyar",
"Brahmakshtriya",
"Brahmbatt",
"Brahmin - All",
"Brahmin - Anavil",
"Brahmin - Audichya",
"Brahmin - Bagra",
"Brahmin - Baragaon",
"Brahmin - Barendra",
"Brahmin - Bhojak",
"Brahmin - Chaubisa",
"Brahmin - Dadhich",
"Brahmin - Daivadnya",
"Brahmin - Dakaut",
"Brahmin - Danua",
"Brahmin - Deshastha",
"Brahmin - Dhiman",
"Brahmin - Dravida",
"Brahmin - Embrandiri",
"Brahmin - Gurukkal",
"Brahmin - Halua",
"Brahmin - Havyaka",
"Brahmin - Hoysala",
"Brahmin - Iyengar",
"Brahmin - Iyer",
"Brahmin - Jangid",
"Brahmin - Jhadua",
"Brahmin - Jyotish",
"Brahmin - Karhade",
"Brahmin - Kokanastha",
"Brahmin - Kota",
"Brahmin - Koteshwara / Kota (Madhwa )",
"Brahmin - Kulin",
"Brahmin - Madhwa",
"Brahmin - Modh",
"Brahmin - Mohyal",
"Brahmin - Nagar",
"Brahmin - Namboodiri",
"Brahmin - Niyogi",
"Brahmin - Paliwal",
"Brahmin - Panda",
"Brahmin - Panicker",
"Brahmin - Rarhi",
"Brahmin - Rigvedi",
"Brahmin - Rudraj",
"Brahmin - Sanketi",
"Brahmin - Shivalli (Madhva)",
"Brahmin - Shivhalli",
"Brahmin - Shri Mali",
"Brahmin - Shrimali",
"Brahmin - Shukla Yajurvedi",
"Brahmin - Sikhwal",
"Brahmin - Smartha",
"Brahmin - Sri Vaishnava",
"Brahmin - Stanika",
"Brahmin - Vaidiki",
"Brahmin - Vaikhanasa",
"Brahmin - Velanadu",
"Brahmin - Vyas",
"Bunt (Shetty)",
"Caste no bar",
"Chakkala Nair",
"Chalawadi and Holeya",
"Chambhar",
"Chandravanshi Kahar",
"Charan",
"Chasa",
"Chattada Sri Vaishnava",
"Chaturth",
"Chaudary",
"Chaurasia",
"Chennadasar",
"Cherakula Vellalar",
"Chero",
"Chettiar",
"Chhetri",
"Chippolu (Mera)",
"Choudhary",
"CKP",
"Coorgi",
"Dasapalanjika / Kannada Saineegar",
"Deshmukh",
"Desikar",
"Desikar Thanjavur",
"Devadiga",
"Devandra Kula Vellalar",
"Devang Koshthi",
"Devanga",
"Devanga Chettiar",
"Devar/Thevar/Mukkulathor",
"Devrukhe Brahmin",
"Dhakad",
"Dhanak",
"Dhangar",
"Dhanka",
"Dhanuk",
"Dheevara",
"Dhiman",
"Dhoba",
"Dhor / Kakkayya",
"Dommala",
"Dosar / Dusra",
"Dumal",
"Dusadh (Paswan)",
"Ediga",
"Ediga /Goud (Balija)",
"Elur Chetty",
"Ezhava",
"Ezhava Panicker",
"Ezhava Thandan",
"Ezhuthachan",
"Gabit",
"Gahoi",
"Gajula / Kavarai",
"Ganda",
"Gandha Vanika",
"Gandharb",
"Gandla",
"Gandla / Ganiga",
"Ganiga",
"Garhwali",
"Garo / Garoda",
"Gatti",
"Gavandi",
"Gavara",
"Gavaria",
"Gawali",
"Ghisadi",
"Ghumar",
"Goala",
"Goan",
"Gomantak",
"Gond",
"Gondhali",
"Gopal / Gopala",
"Goud",
"Gounder",
"Gounder - Kongu Vellala Gounder",
"Gounder - Nattu Gounder",
"Gounder - Others",
"Gounder - Urali Gounder",
"Gounder - Vanniya Kula Kshatriyar",
"Gounder - Vettuva Gounder",
"Gowda",
"Gowda - Kuruba Gowda",
"Gramani",
"Gudia",
"Gujjar",
"Gulahre",
"Gupta",
"Guptan",
"Gurav",
"Gurjar",
"Haihaivanshi",
"Halba Koshti",
"Heggade",
"Helava",
"Holar",
"Hugar (Jeer)",
"Illaththu Pillai",
"Intercaste",
"Irani",
"Isai Vellalar",
"Jaalari",
"Jaiswal",
"Jandra",
"Jangam",
"Jangra - Brahmin",
"Jat",
"Jatav",
"Jetty/Malla",
"Jhadav",
"Jingar",
"Jogi (Nath)",
"Julaha",
"Kachara",
"Kadava Patel",
"Kadia",
"Kahar",
"Kaibarta",
"Kaikaala",
"Kalal",
"Kalanji",
"Kalar",
"Kalbelia",
"Kalinga",
"Kalinga Vysya",
"Kalita",
"Kalwar",
"Kamboj",
"Kamma",
"Kamma Naidu",
"Kanakkan Padanna",
"Kandara",
"Kandera",
"Kanjar",
"Kansari",
"Kansyakaar",
"Kanykubj Bania",
"Kapu",
"Kapu Naidu",
"Kapu Reddy",
"Karakala Bhakthula",
"Karana",
"Karkathar",
"Karmakar",
"Karni Bhakthula",
"Karuneegar",
"Kasar",
"Kasaundhan",
"Kasera",
"Kashyap",
"Kasukara",
"Katiya",
"Kavara",
"Kavuthiyya/Ezhavathy",
"Kayastha",
"Kayastha (Bengali)",
"Kerala Mudali",
"Keshri (Kesarwani)",
"Khandayat",
"Khandelwal",
"Kharwa",
"Kharwar",
"Khatik",
"Khatri",
"Kirar",
"Kodava",
"Kodikal Pillai",
"Kokanastha Maratha",
"Kokna",
"Koli",
"Koli Mahadev",
"Koli Patel",
"Komti /Arya Vaishya",
"Kongu Chettiar",
"Kongu Nadar",
"Kongu Vellala Gounder",
"Konkani",
"Korama",
"Kori",
"Kori/Koli",
"Kosthi",
"Krishnavaka",
"Kshatriya",
"Kshatriya Kurmi",
"Kshatriya Raju",
"Kudumbi",
"Kulal",
"Kulalar",
"Kulita",
"Kumaoni Rajput",
"Kumawat",
"Kumbhakar",
"Kumbhar",
"Kumhar",
"Kummari",
"Kunbi",
"Kunbi Lonari",
"Kunbi Maratha",
"Kunbi Tirale",
"Kuravan",
"Kurmi",
"Kurmi/Kurmi Kshatriya",
"Kurni",
"Kuruba",
"Kuruhina Shetty",
"Kuruhini Chetty",
"Kurumbar",
"Kuruva",
"Kushwaha (Koiri)",
"Kutchi",
"Lad",
"Lambadi",
"Laxminarayan gola",
"Leva patel",
"Leva patil",
"Linga Balija",
"Lingayath",
"Lodhi Rajput",
"Lohana",
"Lohar",
"Loniya",
"Lubana",
"Madhesiya/Kanu/Halwai",
"Madiga",
"Madivala / Dhobi",
"Mahajan",
"Mahar",
"Mahendra",
"Maheshwari",
"Maheshwari / Meshri",
"Mahishya",
"Mahor",
"Mahuri",
"Mair Rajput Swarnkar",
"Majabi",
"Mala",
"Mali",
"Mallah",
"Malwani",
"Mangalorean",
"Manipuri",
"Manjapudur Chettiar",
"Mannadiyar",
"Mannan / Velan / Vannan",
"Mapila",
"Maratha",
"Maratha Kshatriya",
"Maruthuvar",
"Matang",
"Mathur",
"Mathur Vaishya",
"Matia Patel",
"Maurya / Shakya",
"Meena",
"Meenavar",
"Meghwal",
"Mehar",
"Mehra",
"Meru Darji",
"Mochi",
"Modak",
"Modh Ghanchi",
"Modi",
"Modikarlu",
"Mogaveera",
"Mudaliyar",
"Mudiraj",
"Munnuru Kapu",
"Musahar",
"Musukama",
"Muthuraja / Mutharaiyar",
"Naagavamsam",
"Nabit",
"Nadar",
"Nagaralu",
"Nai / Nayi Brahmin",
"Naicker",
"Naicker - Others",
"Naicker - Vanniya Kula Kshatriyar",
"Naidu",
"Naik",
"Nair",
"Namasudra / Namassej",
"Nambiar",
"Namdarlu",
"Nanjil Mudali",
"Nanjil Nattu Vellalar",
"Nanjil pillai",
"Nanjil Vellalar",
"Nankudi Vellalar",
"Napit",
"Nat",
"Nattu Gounder",
"Nattukottai Chettiar",
"Nayaka",
"Neeli",
"Neeli Saali",
"Nema",
"Nepali",
"Nessi",
"Nhavi",
"Niari",
"Odan",
"Ontari",
"Oraon",
"Oswal",
"Otari",
"Othuvaar",
"Padmasali",
"Padmashali",
"Padmavati Porwal",
"Pagadala",
"Pal",
"Pallan / Devandra Kula Vellalan",
"Panan",
"Panchal",
"Pandaram",
"Pandiya Vellalar",
"Panicker",
"Pannirandam Chettiar",
"Paravan / Bharatar",
"Parit",
"Parkavakulam / Udayar",
"Parsi",
"Partraj",
"Parvatha Rajakulam",
"Pasi",
"Paswan / Dusadh",
"Patel",
"Pathare Prabhu",
"Patil",
"Patnaick/Sistakaranam",
"Patra",
"Pattinavar",
"Pattusali",
"Patwa",
"Perika",
"Perika/Puragiri Kshatriya",
"Pillai",
"Poddar",
"Poosala",
"Porwal",
"Porwal / Porwar",
"Poundra",
"Prajapati",
"Pulaya / Cheruman",
"Rabari",
"Radhi / Niari",
"Raigar",
"Rajaka / Vannar",
"Rajastani",
"Rajbhar",
"Rajbonshi",
"Rajpurohit",
"Rajput",
"Raju / Kshatriya Raju",
"Ramanandi",
"Ramdasia",
"Ramgariah",
"Ramoshi",
"Rastogi",
"Rathi",
"Rauniar",
"Ravana Rajput",
"Ravidasia",
"Rawat",
"Reddy",
"Relli",
"Rohit / Chamar",
"Ror",
"Sadgope",
"Sadhu Chetty",
"Sagara (Uppara)",
"Saha",
"Sahariya",
"Sahu",
"Saini",
"Saiva Pillai Thanjavur",
"Saiva Pillai Tirunelveli",
"Saiva Vellan chettiar",
"Saliya",
"Saliyar",
"Salvi",
"Samagar",
"Sambava",
"Sansi",
"Sargara",
"Sathwara",
"Satnami",
"Savji",
"SC",
"Senai Thalaivar",
"Senguntha Mudaliyar",
"Sengunthar/Kaikolar",
"Settibalija",
"Setty Balija",
"Shah",
"Shaw / Sahu/Teli",
"Shettigar",
"Shilpkar",
"Shimpi/Namdev",
"Sindhi",
"Sindhi-Amil",
"Sindhi-Baibhand",
"Sindhi-Bhanusali",
"Sindhi-Bhatia",
"Sindhi-Chhapru",
"Sindhi-Dadu",
"Sindhi-Hyderabadi",
"Sindhi-Larai",
"Sindhi-Larkana",
"Sindhi-Lohana",
"Sindhi-Rohiri",
"Sindhi-Sahiti",
"Sindhi-Sakkhar",
"Sindhi-Sehwani",
"Sindhi-Shikarpuri",
"Sindhi-Thatai",
"Sirvi / Janwa",
"SKP",
"Sonar",
"Sondhia",
"Soni",
"Sonkar",
"Sourashtra",
"Sozhia Chetty",
"Sozhiya Vellalar",
"Srisayana",
"ST",
"Sugali (Naika)",
"Sunari",
"Sundhi",
"Surya Balija",
"Suthar",
"Swakula Saali",
"Swakula Sali",
"Swarnakar",
"Tamboli",
"Tammali",
"Tanti",
"Tantubai",
"Telaga",
"Teli",
"Telugupatti",
"Thakkar",
"Thakore",
"Thakur",
"Thandan",
"Tharakan",
"Thigala",
"Thiyya",
"Thiyya Thandan",
"Thogata Veera Kshatriya",
"Thogata Veerakshathriya",
"Thondai Mandala Vellalar",
"Thota",
"Tili",
"Tiyar/Tiar",
"Togata",
"Tonk Kshatriya",
"Turupu Kapu",
"Ummar / Umre / Bagaria",
"Urali Gounder",
"Urs",
"Vada Balija",
"Vadambar",
"Vadar",
"Vaddera",
"Vadugan",
"Vaish",
"Vaishnav",
"Vaishnav Dishaval",
"Vaishnav Kapol",
"Vaishnav Khadyata",
"Vaishnav Lad",
"Vaishnav Modh",
"Vaishnav Porvad",
"Vaishnav Shrimali",
"Vaishnav Sorathaiya",
"Vaishnav Vania",
"Vaishnava",
"Vaishya",
"Vaishya Vani",
"Valar",
"Valluvan",
"Valmiki",
"Valsad",
"Vani",
"Vani / Vaishya",
"Vania",
"Vanika Vyshya",
"Vaniya",
"Vaniya Chettiar",
"Vanjara",
"Vanjari",
"Vankar",
"Vannar",
"Vannia Kula Kshatriyar",
"Vanyakulakshatriya",
"Variar",
"Varshney",
"Varshney (Barahseni)",
"Veera Saivam",
"Veerakodi Vellala",
"Velaan",
"Velama",
"Vellala Pillai",
"Vellalar",
"Vellan Chettiars",
"Veluthedathu Nair",
"Vettuva Gounder",
"Vettuvan",
"Vijayvargia",
"Vilakithala Nair",
"Vilakkithala Nair",
"Vishwakarma",
"Viswabrahmin",
"Vokkaliga",
"Vysya",
"Yadav",
"Yadava Naidu",
"Yellapu",
]



Muslim=[
"Muslim - Ansari",
"Muslim - Arain",
"Muslim - Awan",
"Muslim - Bohra",
"Muslim - Dekkani",
"Muslim - Dudekula",
"Muslim - Hanafi",
"Muslim - Jat",
"Muslim - Khoja",
"Muslim - Lebbai",
"Muslim - Malik",
"Muslim - Mapila",
"Muslim - Maraicar",
"Muslim - Memon",
"Muslim - Mughal",
"Muslim - Others",
"Muslim - Pathan",
"Muslim - Qureshi",
"Muslim - Rajput",
"Muslim - Rowther",
"Muslim - Shafi",
"Muslim - Sheikh",
"Muslim - Siddiqui",
"Muslim - Syed",
"Muslim - UnSpecified",


]


Christian=[
    "Adventist",
"Anglican / Episcopal",
"Anglo-Indian",
"Apostolic",
"Assembly of God (AG)",
"Baptist",
"Born Again",
"Brethren",
"Calvinist",
"Caste no bar",
"Chaldean Syrian (Assyrian)",
"Church of Christ",
"Church of God",
"Church of North India",
"Church of South India",
"Congregational",
"Evangelist",
"Jacobite",
"Jehovah's Witnesses",
"Knanaya",
"Knanaya Catholic",
"Knanaya Jacobite",
"Latin Catholic",
"Latter day saints",
"Lutheran",
"Malabar Independent Syrian Church",
"Malankara catholic",
"Marthoma",
"Melkite",
"Mennonite",
"Methodist",
"Moravian",
"Orthodox",
"Others",
"Pentecost",
"Presbyterian",
"Protestant",
"Reformed Baptist",
"Reformed Presbyterian",
"Roman Catholic",
"Seventh-day Adventist",
"St. Thomas Evangelical",
"Syrian Catholic",
"Syrian Jacobite",
"Syrian Orthodox",
"Syro Malabar",


]


Sikh=[
"Sikh - Ahluwalia",
"Sikh - Arora",
"Sikh - Bhatia",
"Sikh - Bhatra",
"Sikh - Ghumar",
"Sikh - Intercaste",
"Sikh - Jat",
"Sikh - Kamboj",
"Sikh - Khatri",
"Sikh - Kshatriya",
"Sikh - Lubana",
"Sikh - Majabi",
"Sikh - Nai",
"Sikh - Others",
"Sikh - Rai",
"Sikh - Rajput",
"Sikh - Ramdasia",
"Sikh - Ramgharia",
"Sikh - Ravidasia",
"Sikh - Saini",
"Sikh - Tonk Kshatriya",
"Sikh - Unspecified",


]


Jain=[
"Jain - Agarwal",
"Jain - Asati",
"Jain - Ayodhyavasi",
"Jain - Bagherwal",
"Jain - Bania",
"Jain - Barhiya",
"Jain - Charanagare",
"Jain - Chaturtha",
"Jain - Dhakada",
"Jain - Gahoi / Grihapati",
"Jain - Golalare / Kharaua",
"Jain - Golapurva",
"Jain - Golsinghare",
"Jain - Harada",
"Jain - Humad / Humbad",
"Jain - Intercaste",
"Jain - Jaiswal",
"Jain - KVO",
"Jain - Kambhoja",
"Jain - Kasar",
"Jain - Kathanere",
"Jain - Khandelwal",
"Jain - Kharaua",
"Jain - Kutchi",
"Jain - Lamechu",
"Jain - Nema",
"Jain - Oswal",
"Jain - Others",
"Jain - Padmavati Porwal",
"Jain - Palliwal",
"Jain - Panchama",
"Jain - Parmar",
"Jain - Parwar / Paravara",
"Jain - Porwad / Porwal",
"Jain - Porwal",
"Jain - Saitwal",
"Jain - Samanar / Nayinar",
"Jain - Samiya",
"Jain - Sarak",
"Jain - Shrimal",
"Jain - Unspecified",
"Jain - Upadhyaya",
"Jain - Vaishya",
"Jain - Veerwal",
]
Parsi=["Irani", "Parsi"]
Buddhist=["Neo Buddhist","Tibetan Buddhist","Others"]



Religion=["Hindu", "Muslim", "Christian", "Sikh", "Jain", "Parsi", "Buddhist"]
Hindus=["Hindi","Bihari","Marathi","Gujarati",
              "Marwadi","Punjabi","Oriya","Bengali","Assamese",
              "Rajasthani","Telugu","Kannada","Tamil","Kerala","Sindhi"
              ]
Muslims=["Muslim"]
Christians=["Christians"]
Sikhs=["Sikhs"]
Jains=['Jains']
Parsis=['Parsi']
Buddhists=['Buddhist']